name: Flutter Analyze

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  analyze:
    name: Run Flutter Analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Analyze project
        run: flutter analyze --fatal-infos
